name: jason bobango
favicon: null
layout_spectrum: 0.2497633839957416
typography_spectrum: 0.11372062121517956
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2328953098040074
  lightness: 0.126288958825171
  saturation: 0.923827389953658
  rhythmicContrast: 0.38071283511817455
purpose: []
